import re

path = r'd:\nckh\rai_website\client\src\app\(dashboard)\analytics\page.tsx'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update ControlSection
content = content.replace(
    'function ControlSection({ summary, series, loading, onDownload }: {\n  summary: AnalyticsSummary | null; series: Snapshot[]; loading: boolean;\n  onDownload: (ep: string, fn: string) => Promise<void>;\n}) {\n  const w = summary?.window;\n  const chartData = useMemo(() =>\n    series.map((s) => ({\n      t: new Date(s.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),\n      speed: s.speed ?? null,\n    })), [series]);\n\n  const dominantMode = w\n    ? Object.entries(w.navigation_modes ?? {}).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "—"\n    : "—";',
    'function ControlSection({ summary, series, trials, loading, onDownload }: {\n  summary: AnalyticsSummary | null; series: Snapshot[]; trials: ExperimentTrial[]; loading: boolean;\n  onDownload: (ep: string, fn: string) => Promise<void>;\n}) {\n  const w = summary?.window;\n  const chartData = useMemo(() =>\n    series.map((s) => ({\n      t: new Date(s.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),\n      speed: s.speed ?? null,\n    })), [series]);\n\n  const dominantMode = w\n    ? Object.entries(w.navigation_modes ?? {}).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "—"\n    : "—";\n\n  const tStop = trials.find(t => t.stop_distance_m != null);\n  const stopDist = tStop ? `${tStop.stop_distance_m} m` : "— pending trial";\n  const badgeStop = tStop ? "trial data" : "pending trial";\n\n  const tNav = trials.filter(t => t.success_count != null && t.total_count != null);\n  let navGoal = "— pending trial";\n  let badgeNav = "pending trial";\n  if (tNav.length > 0) {\n    const sumS = tNav.reduce((acc, t) => acc + (t.success_count || 0), 0);\n    const sumT = tNav.reduce((acc, t) => acc + (t.total_count || 0), 0);\n    navGoal = `${((sumS / sumT) * 100).toFixed(1)}%`;\n    badgeNav = "trial data";\n  }'
)

content = content.replace(
    '<StatRow label="Khoảng cách stop thực tế" value="— pending trial" badge="pending trial" loading={loading} />\n          <StatRow label="Navigation mode" value={dominantMode} loading={loading} />\n          <StatRow label="Tỷ lệ đến Goal Nav2" value="— pending trial" badge="pending trial" loading={loading} />',
    '<StatRow label="Khoảng cách stop thực tế" value={stopDist} badge={badgeStop} loading={loading} />\n          <StatRow label="Navigation mode" value={dominantMode} loading={loading} />\n          <StatRow label="Tỷ lệ đến Goal Nav2" value={navGoal} badge={badgeNav} loading={loading} />'
)

# 2. Update PerceptionSection
content = content.replace(
    'function PerceptionSection({ summary, series, loading, onDownload }: {\n  summary: AnalyticsSummary | null; series: Snapshot[]; loading: boolean;\n  onDownload: (ep: string, fn: string) => Promise<void>;\n}) {\n  const w = summary?.window;\n  const fpsData = useMemo(() =>\n    series.map((s) => ({\n      t: new Date(s.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),\n      fps: s.ai_fps ?? null,\n    })), [series]);',
    'function PerceptionSection({ summary, series, trials, loading, onDownload }: {\n  summary: AnalyticsSummary | null; series: Snapshot[]; trials: ExperimentTrial[]; loading: boolean;\n  onDownload: (ep: string, fn: string) => Promise<void>;\n}) {\n  const w = summary?.window;\n  const fpsData = useMemo(() =>\n    series.map((s) => ({\n      t: new Date(s.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),\n      fps: s.ai_fps ?? null,\n    })), [series]);\n\n  const tDet = trials.find(t => t.scenario === "detector_eval");\n  const tTrk = trials.find(t => t.scenario === "tracker_eval");\n  const tInt = trials.find(t => t.scenario === "intent_eval");\n\n  const valLatDet = tDet ? `${tDet.detector_latency_avg_ms}ms / ${tDet.detector_latency_p95_ms}ms` : "— pending profiler";\n  const valTrack = tTrk ? `sw: ${tTrk.tracker_id_switch_rate} | loss: ${tTrk.tracker_loss_rate}` : "— pending tracker log";\n  const valLatInt = tInt ? `${tInt.intent_latency_avg_ms}ms / ${tInt.intent_latency_p95_ms}ms` : "— pending profiler";\n  const valAccInt = tInt ? `${(tInt.intent_accuracy ?? 0) * 100}%` : "— pending eval";\n  const valEceInt = tInt ? `${tInt.intent_ece}` : "— pending eval";\n  const valUncInt = tInt ? `${((tInt.intent_uncertain_rate ?? 0) * 100).toFixed(1)}%` : "— pending runtime log";'
)

content = content.replace(
    '<StatRow label="Latency YOLO (avg / p95)" value="— pending profiler" badge="pending trial" loading={loading} />\n          <StatRow label="ID switch / track loss" value="— pending tracker log" badge="pending trial" loading={loading} />\n          <StatRow label="Latency Temporal Intent CNN" value="— pending profiler" badge="pending trial" loading={loading} />\n          <StatRow label="Accuracy 5 lớp trainable" value="— pending eval" badge="pending eval" loading={loading} />\n          <StatRow label="ECE và calibration" value="— pending eval" badge="pending eval" loading={loading} />\n          <StatRow label="Tỷ lệ UNCERTAIN" value="— pending runtime log" badge="pending trial" loading={loading} />',
    '<StatRow label="Latency YOLO (avg / p95)" value={valLatDet} badge={tDet ? "trial data" : "pending trial"} loading={loading} />\n          <StatRow label="ID switch / track loss" value={valTrack} badge={tTrk ? "trial data" : "pending trial"} loading={loading} />\n          <StatRow label="Latency Temporal Intent CNN" value={valLatInt} badge={tInt ? "trial data" : "pending trial"} loading={loading} />\n          <StatRow label="Accuracy 5 lớp trainable" value={valAccInt} badge={tInt ? "trial data" : "pending eval"} loading={loading} />\n          <StatRow label="ECE và calibration" value={valEceInt} badge={tInt ? "trial data" : "pending eval"} loading={loading} />\n          <StatRow label="Tỷ lệ UNCERTAIN" value={valUncInt} badge={tInt ? "trial data" : "pending trial"} loading={loading} />'
)

# 3. Update DatasetSection
content = content.replace(
    'function DatasetSection({ loading, onDownload }: { loading: boolean; onDownload: (ep: string, fn: string) => Promise<void> }) {\n  const rows = [\n    "Tổng số ROI", "Số track hợp lệ", "Phân phối lớp (5 class)",\n    "Duplicate", "Corrupt", "Pending review", "Số sample trainable",\n  ];',
    'function DatasetSection({ trials, loading, onDownload }: { \n  trials: ExperimentTrial[]; loading: boolean; \n  onDownload: (ep: string, fn: string) => Promise<void> \n}) {\n  const tDat = trials.find(t => t.scenario === "dataset_gate");\n  const getVal = (v: number | null | undefined, suffix = "") => tDat && v != null ? `${v}${suffix}` : "— pending data";\n  const rows = [\n    { label: "Tổng số ROI", value: getVal(tDat?.dataset_total_samples) },\n    { label: "Số track hợp lệ", value: getVal(tDat?.dataset_min_class_count) },\n    { label: "Phân phối lớp (5 class)", value: tDat ? "Balanced" : "— pending data" },\n    { label: "Duplicate", value: getVal(tDat?.dataset_duplicate_rate, "%") },\n    { label: "Corrupt", value: getVal(tDat?.dataset_corrupt_rate, "%") },\n    { label: "Pending review", value: getVal(tDat?.dataset_pending_review_rate, "%") },\n    { label: "Số sample trainable", value: getVal(tDat?.dataset_total_samples) },\n  ];'
)

content = content.replace(
    '{rows.map((label) => (\n            <StatRow key={label} label={label} value="— pending dataset API" badge="pending pipeline" loading={loading} />\n          ))}',
    '{rows.map((r) => (\n            <StatRow key={r.label} label={r.label} value={r.value} badge={tDat ? "trial data" : "pending pipeline"} loading={loading} />\n          ))}'
)

# 4. Update ExperimentPanel
content = content.replace(
    'function ExperimentPanel({ download }: { download: (ep: string, fn: string) => Promise<void> }) {\n  const [trials, setTrials] = useState<ExperimentTrial[]>([]);\n  const [total, setTotal] = useState(0);\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    const run = async () => {\n      try {\n        const res = await fetchWithAuth("/api/experiments/trials?limit=20");\n        const data = (await res.json()) as ExperimentList;\n        setTrials(data.items);\n        setTotal(data.total);\n      } catch { /* keep stale */ } finally { setLoading(false); }\n    };\n    void run();\n  }, []);\n\n  return (',
    'function ExperimentPanel({ trials, total, loading, download }: { \n  trials: ExperimentTrial[]; total: number; loading: boolean; \n  download: (ep: string, fn: string) => Promise<void> \n}) {\n  return ('
)

# 5. Update AnalyticsPage
content = content.replace(
    'export default function AnalyticsPage() {\n  const [summary, setSummary] = useState<AnalyticsSummary | null>(null);\n  const [series, setSeries] = useState<Snapshot[]>([]);\n  const [loading, setLoading] = useState(true);\n  const [refreshing, setRefreshing] = useState(false);\n  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);\n  const download = useCSVDownload();\n\n  const load = useCallback(async (manual = false) => {\n    if (manual) setRefreshing(true);\n    try {\n      const [sumRes, serRes] = await Promise.all([\n        fetchWithAuth("/api/analytics/summary?hours=24"),\n        fetchWithAuth("/api/analytics/timeseries?hours=6&limit=240"),\n      ]);\n      setSummary((await sumRes.json()) as AnalyticsSummary);\n      setSeries((await serRes.json()) as Snapshot[]);\n      setLastUpdated(new Date());\n    } catch { /* keep stale */ } finally {\n      setLoading(false);\n      setRefreshing(false);\n    }\n  }, []);',
    'export default function AnalyticsPage() {\n  const [summary, setSummary] = useState<AnalyticsSummary | null>(null);\n  const [series, setSeries] = useState<Snapshot[]>([]);\n  const [trials, setTrials] = useState<ExperimentTrial[]>([]);\n  const [totalTrials, setTotalTrials] = useState(0);\n  const [loading, setLoading] = useState(true);\n  const [refreshing, setRefreshing] = useState(false);\n  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);\n  const download = useCSVDownload();\n\n  const load = useCallback(async (manual = false) => {\n    if (manual) setRefreshing(true);\n    try {\n      const [sumRes, serRes, trialRes] = await Promise.all([\n        fetchWithAuth("/api/analytics/summary?hours=24"),\n        fetchWithAuth("/api/analytics/timeseries?hours=6&limit=240"),\n        fetchWithAuth("/api/experiments/trials?limit=100")\n      ]);\n      setSummary((await sumRes.json()) as AnalyticsSummary);\n      setSeries((await serRes.json()) as Snapshot[]);\n      const trialData = await trialRes.json() as any;\n      setTrials(trialData.items || []);\n      setTotalTrials(trialData.total || 0);\n      setLastUpdated(new Date());\n    } catch { /* keep stale */ } finally {\n      setLoading(false);\n      setRefreshing(false);\n    }\n  }, []);'
)

content = content.replace(
    '<ControlSection summary={summary} series={series} loading={loading} onDownload={download} />\n      <PerceptionSection summary={summary} series={series} loading={loading} onDownload={download} />\n      <DatasetSection loading={loading} onDownload={download} />\n      <SafetySection summary={summary} loading={loading} onDownload={download} />\n      <ExperimentPanel download={download} />',
    '<ControlSection summary={summary} series={series} trials={trials} loading={loading} onDownload={download} />\n      <PerceptionSection summary={summary} series={series} trials={trials} loading={loading} onDownload={download} />\n      <DatasetSection trials={trials} loading={loading} onDownload={download} />\n      <SafetySection summary={summary} loading={loading} onDownload={download} />\n      <ExperimentPanel trials={trials} total={totalTrials} loading={loading} download={download} />'
)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print("PATCH SUCCESS!")
